sudo: false
language: android
jdk:
  - oraclejdk7

android:
    components:
#      - build-tools-24.0.0 rc1
      - build-tools-23.0.3
      - android-23
      - extra

before_script:
  - chmod +x gradlew

script:
    - ./gradlew check --info

